# Generated by Django 5.0.4 on 2024-04-27 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.IntegerField(null=True),
        ),
    ]
