# Generated by Django 5.0.4 on 2024-04-27 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materia', '0001_initial'),
        ('profesor', '0001_initial'),
        ('publicacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='profesores',
            field=models.ManyToManyField(through='publicacion.Publicacion', to='profesor.profesor'),
        ),
    ]
